#!/bin/bash
set -e

source ./bin/control/set_env
ACTION=${1-restart}

if [ -f /bin/systemctl ]; then
	echo "systemctl ${ACTION} ${ServiceName}"
	systemctl ${ACTION} ${ServiceName}
else
	echo "service ${ServiceName} ${ACTION}"
	service ${ServiceName} ${ACTION}
fi

if [ $? ] ; then
	echo "service ${ACTION} complete"
else
	echo "can't ${ACTION} service"
fi
