#!/bin/bash

. ./bin/control/set_env

if [ -f /bin/systemctl ]; then
	systemctl stop ${ServiceName}
else
	service ${ServiceName} stop
fi

set -e

if [ -f ${FinalFile} ]; then
	echo "unlink ${FinalFile}"
	unlink ${FinalFile}
fi

if [ -f ${TargetFile} ]; then
	echo "unlink ${TargetFile}"
	unlink ${TargetFile}
fi
