#!/bin/bash
set -e

branch_name=$(git symbolic-ref -q HEAD)
branch_name=${branch_name##refs/heads/}
branch_name=${branch_name:-HEAD}

if [ "${branch_name}" != "online" ]; then
	echo -e "not on branch \x1B[38;5;9m 'online' \x1B[0m"
	exit 2
fi

echo -e ">>>\e[38;5;14m update code from git repo \e[0m<<<"

git fetch origin online
git checkout online
git reset --hard
git pull

echo -e ">>>\e[38;5;14m update jenv \e[0m<<<"
jenv --download
 
echo -e ">>>\e[38;5;14m build docker \e[0m<<<"
jenv ./bin/control/build

echo -e ">>>\e[38;5;14m restart docker container \e[0m<<<"
./bin/control/restart
